/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as PoliceRouteImport } from './routes/police'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliceSchoolIdRouteImport } from './routes/police.$schoolId'

const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliceRoute = PoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliceSchoolIdRoute = PoliceSchoolIdRouteImport.update({
  id: '/$schoolId',
  path: '/$schoolId',
  getParentRoute: () => PoliceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/police': typeof PoliceRouteWithChildren
  '/school': typeof SchoolRoute
  '/police/$schoolId': typeof PoliceSchoolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/police': typeof PoliceRouteWithChildren
  '/school': typeof SchoolRoute
  '/police/$schoolId': typeof PoliceSchoolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/police': typeof PoliceRouteWithChildren
  '/school': typeof SchoolRoute
  '/police/$schoolId': typeof PoliceSchoolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/police' | '/school' | '/police/$schoolId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/police' | '/school' | '/police/$schoolId'
  id: '__root__' | '/' | '/login' | '/police' | '/school' | '/police/$schoolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PoliceRoute: typeof PoliceRouteWithChildren
  SchoolRoute: typeof SchoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/police': {
      id: '/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof PoliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/police/$schoolId': {
      id: '/police/$schoolId'
      path: '/$schoolId'
      fullPath: '/police/$schoolId'
      preLoaderRoute: typeof PoliceSchoolIdRouteImport
      parentRoute: typeof PoliceRoute
    }
  }
}

interface PoliceRouteChildren {
  PoliceSchoolIdRoute: typeof PoliceSchoolIdRoute
}

const PoliceRouteChildren: PoliceRouteChildren = {
  PoliceSchoolIdRoute: PoliceSchoolIdRoute,
}

const PoliceRouteWithChildren =
  PoliceRoute._addFileChildren(PoliceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PoliceRoute: PoliceRouteWithChildren,
  SchoolRoute: SchoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
